# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#7fbbb3" }

# Find
find_keyword  = { fg = "#dbbc7f", bold = true, italic = true, underline = true }
find_position = { fg = "#d699b6", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#a7c080", bg = "#a7c080" }
marker_cut      = { fg = "#e67e80", bg = "#e67e80" }
marker_marked   = { fg = "#7fbbb3", bg = "#7fbbb3" }
marker_selected = { fg = "#dbbc7f", bg = "#dbbc7f" }

# Count
count_copied   = { fg = "#343f44", bg = "#a7c080" }
count_cut      = { fg = "#343f44", bg = "#e67e80" }
count_selected = { fg = "#343f44", bg = "#dbbc7f" }

# Border
border_symbol = "│"
border_style  = { fg = "#4f585e" }

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#343f44", bg = "#a7c080", bold = true }
inactive = { fg = "#a7c080", bg = "#4f585e" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#343f44", bg = "#a7c080", bold = true }
normal_alt  = { fg = "#a7c080", bg = "#4f585e" }

# Select mode
select_main = { fg = "#343f44", bg = "#7fbbb3", bold = true }
select_alt  = { fg = "#7fbbb3", bg = "#4f585e" }

# Unset mode
unset_main = { fg = "#343f44", bg = "#dbbc7f", bold = true }
unset_alt  = { fg = "#dbbc7f", bg = "#4f585e" }

# : }}}


# : Status bar {{{

[status]
# Permissions
perm_sep   = { fg = "#4f585e" }
perm_type  = { fg = "#a7c080" }
perm_read  = { fg = "#dbbc7f" }
perm_write = { fg = "#e67e80" }
perm_exec  = { fg = "#a7c080" }

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#a7c080", bg = "#4f585e" }
progress_error  = { fg = "#dbbc7f", bg = "#e67e80" }

# : }}}


# : Pick {{{

[pick]
border   = { fg = "#a7c080" }
active   = { fg = "#d699b6", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#a7c080" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#a7c080" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#a7c080" }
title   = {}
hovered = { fg = "#d699b6", bold = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#4f585e" }
cand            = { fg = "#7fbbb3" }
rest            = { fg = "#9da9a0" }
desc            = { fg = "#d699b6" }
separator       = "  "
separator_style = { fg = "#5a6369" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#7fbbb3" }
run     = { fg = "#d699b6" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#4f585e", bg = "#d3c6aa" }

# : }}}


# : Spotter {{{

[spot]
border   = { fg = "#a7c080" }
title    = { fg = "#a7c080" }
tbl_col  = { fg = "#7fbbb3" }
tbl_cell = { fg = "#d699b6", bg = "#4f585e" }

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "#a7c080" }
title_warn  = { fg = "#dbbc7f" }
title_error = { fg = "#e67e80" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Image
	{ mime = "image/*", fg = "#7fbbb3" },
	# Media
	{ mime = "{audio,video}/*", fg = "#dbbc7f" },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#d699b6" },
	# Document
	{ mime = "application/{pdf,doc,rtf}", fg = "#a7c080" },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#9da9a0" },
	# Fallback
	{ url = "*", fg = "#d3c6aa" },
	{ url = "*/", fg = "#a7c080" },
]

# : }}}

[icon]

dirs = [
	{ name = ".config", text = "", fg = "#d699b6" },
	{ name = ".git", text = "", fg = "#7fbbb3" },
	{ name = ".github", text = "", fg = "#a7c080" },
	{ name = ".npm", text = "", fg = "#a7c080" },
	{ name = "Desktop", text = "", fg = "#7fbbb3" },
	{ name = "Development", text = "", fg = "#7fbbb3" },
	{ name = "Documents", text = "", fg = "#7fbbb3" },
	{ name = "Downloads", text = "", fg = "#7fbbb3" },
	{ name = "Library", text = "", fg = "#7fbbb3" },
	{ name = "Movies", text = "", fg = "#7fbbb3" },
	{ name = "Music", text = "", fg = "#7fbbb3" },
	{ name = "Pictures", text = "", fg = "#7fbbb3" },
	{ name = "Public", text = "", fg = "#7fbbb3" },
	{ name = "Videos", text = "", fg = "#7fbbb3" },
]
conds = [
	# Special files
	{ if = "orphan", text = "", fg = "#d3c6aa" },
	{ if = "link", text = "", fg = "#4f585e" },
	{ if = "block", text = "", fg = "#dbbc7f" },
	{ if = "char", text = "", fg = "#dbbc7f" },
	{ if = "fifo", text = "", fg = "#dbbc7f" },
	{ if = "sock", text = "", fg = "#dbbc7f" },
	{ if = "sticky", text = "", fg = "#dbbc7f" },
	{ if = "dummy", text = "", fg = "#e67e80" },

	# Fallback
	{ if = "dir", text = "", fg = "#a7c080" },
	{ if = "exec", text = "", fg = "#a7c080" },
	{ if = "!dir", text = "", fg = "#d3c6aa" },
]
